Repository WildCodeSchool/2024-12-orleans-cda-project2-team-c, pull requests merged in 2025-02, with the labels that each got.

#15 Quiz start page
  src/assets/images/114.png
  src/components/quiz-game.jsx
  src/components/quiz-start.jsx
  src/css/carousel.css
  src/css/quiz.css
  src/main.css
  src/main.jsx
  src/pages/quiz.jsx
  src/utils/api-connection.jsx
Labels: Sylvain

#16 Set up game classes for quiz handling
  src/components/quiz-game.jsx
  src/components/quiz-start.jsx
  src/css/quiz.css
  src/models/Game.js
  src/models/Round.js
  src/pages/quiz.jsx
  src/utils/pokemon-names.js
Labels: changes requested

#17 Feature/pokemon display
  src/components/button.jsx
  src/css/badge-type.css
  src/css/button.css
  src/css/pokemon-display.css
  src/main.css
  src/main.jsx
  src/pages/pokemon-display.jsx
Labels: Sylvain

#19 Feature/error 404
  src/assets/images/error-404-mewtwo.png
  src/css/error-404.css
  src/css/pokemon-display.css
  src/pages/error-404.jsx
Labels: Sylvain

#20 Feature/quiz game
  src/components/button.jsx
  src/components/quiz-game.jsx
  src/css/quiz.css
  src/models/Game.js
  src/models/Round.js
Labels: Sylvain

#21 button up
  src/components/button-up.jsx
  src/css/button-up.css
  src/pages/pokedex.jsx
  src/pages/pokemon-list.jsx
Labels: Sylvain

#22 Feature/results display
  src/components/quiz-results.jsx
  src/css/error-404.css
  src/css/quiz.css
  src/main.css
  src/pages/error-404.jsx
Labels: Sylvain

#23 Feature/quiz game
  .gitignore
  src/components/quiz-game.jsx
  src/components/quiz-results.jsx
  src/css/button.css
  src/css/pokemon-display.css
  src/css/quiz.css
  src/main.css
  src/models/Round.js
  src/pages/quiz.jsx
  src/utils/api-connection.jsx
Labels: Sylvain

#24 Feature/storage
  src/components/quiz-game.jsx
  src/main.jsx
  src/pages/pokedex.jsx
Labels: Sylvain

#25 search bar
  src/components/search-section.jsx
  src/css/search-section.css
Labels: Sylvain

#26 Feature/bugfix
  src/components/carousel.jsx
  src/components/header.jsx
  src/components/quiz-game.jsx
  src/css/button.css
  src/css/carousel.css
  src/css/footer.css
  src/main.css
  src/pages/home.jsx
  src/pages/pokedex.jsx
Labels: Sylvain

#27 fix bugs
  src/main.jsx
  src/pages/pokedex.jsx
  src/pages/pokemon-list.jsx
Labels: Sylvain

#29 fix bugs
  src/components/pokemon-card.jsx
  src/components/quiz-game.jsx
  src/components/quiz-results.jsx
  src/pages/quiz.jsx
Labels: Sylvain

#28 Feature/pokedex
  .gitignore
  src/components/search-section.jsx
  src/css/carousel.css
  src/css/quiz.css
  src/css/search-section.css
  src/mock-pokemons.js
Labels: Sylvain

#30 modif badge and css
  src/components/badge-type.jsx
  src/css/badge-type.css
  src/css/quiz.css
  src/main.css
Labels: Sylvain

#31 pokemon-card modification
  src/components/pokemon-card.jsx
  src/css/pokemon-card.css
  src/css/search-section.css
  src/main.css
  src/pages/pokemon-list.jsx
Labels: Sylvain

#32 fix bug can answer after timer ends
  src/components/quiz-game.jsx
Labels: Sylvain

#33 Feature/responsive quiz
  .gitignore
  src/components/quiz-game.jsx
  src/css/header.css
  src/css/pokemon-display.css
  src/css/quiz.css
Labels: Sylvain

#34 no panayim nakudotayim allowed in this case
  src/css/button.css
Labels: Sylvain

#35 responsiv pokemon card
  src/assets/icons/new-gold-badge.png
  src/components/pokemon-card.jsx
  src/components/quiz-game.jsx
  src/components/quiz-results.jsx
  src/css/button-up.css
  src/css/pokemon-card.css
  src/css/quiz.css
  src/css/search-section.css
  src/models/Round.js
Labels: Sylvain

#36 add search by name in pokemon display page
  src/components/search-section.jsx
  src/main.jsx
  src/utils/api-connection.jsx
Labels: Sylvain

#37 last bugs fix
  src/components/quiz-start.jsx
  src/css/header.css
  src/css/quiz.css
Labels: Sylvain

#39 Feature/bugfix
  public/bg-pattern-2.jpg
  public/bg-pattern-2.png
  src/App.jsx
  src/components/quiz-game.jsx
  src/css/header.css
  src/main.css
Labels: Sylvain

#40 review by Yahya
  src/components/carousel.jsx
  src/components/pokemon-card.jsx
  src/components/stats.jsx
  src/css/carousel.css
  src/css/pokemon-card.css
  src/css/pokemon-list.css
  src/pages/home.jsx
  src/pages/pokedex.jsx
Labels: Sylvain

#41 Feature/eric
  src/main.jsx
Labels: Sylvain

#44 changes asked for in PR
  src/components/quiz-game.jsx
  src/models/Game.js
  src/pages/error-404.jsx
Labels: changes requested

#48 Release/bulbasaur
  src/components/header.jsx
  src/components/quiz-game.jsx
  src/components/search-section.jsx
  src/css/header.css
  src/css/pokemon-display.css
  src/css/pokemon-list.css
  src/css/quiz.css
  src/css/search-section.css
  src/main.css
  src/models/Game.js
  src/pages/error-404.jsx
  src/pages/pokedex.jsx
  src/pages/pokemon-list.jsx
Labels: Sylvain

#49 fix typo
  vite.config.prod.js
Labels: Sylvain

#50 fix typo
  .github/workflows/deploy.yml
  vite.config.prod.js
Labels: Sylvain

#51 bug rsolve
  src/components/quiz-game.jsx
  src/css/quiz.css
  src/main.jsx
Labels: Sylvain

#52 Hotfix/pikapika
  src/components/quiz-game.jsx
  src/css/quiz.css
  src/main.jsx
Labels: Sylvain

#54 fix landing page link and burger menu
  src/components/header.jsx
  src/css/header.css
Labels: Sylvain

#53 Hotfix/celebi
  src/components/header.jsx
  src/css/header.css
Labels: à review

#55 last fix burger menu and search input bugs
  src/components/button.jsx
  src/components/header.jsx
  src/css/quiz.css
Labels: Sylvain

#56 Hotfix/pecharunt
  src/components/button.jsx
  src/components/header.jsx
  src/css/quiz.css
Labels: Sylvain

#57 last fix burger king
  src/components/header.jsx
Labels: Sylvain

#58 last fix burger king
  src/components/header.jsx
Labels: Sylvain

#59 Hotfix/footer links
  public/icons/facebook-white-64.png
  public/icons/instagram-white-64.png
  src/components/footer.jsx
  src/css/footer.css
Labels: Sylvain

#60 Hotfix/footer links
  .github/workflows/deploy.yml
  public/icons/facebook-white-64.png
  public/icons/instagram-white-64.png
  src/components/footer.jsx
  src/css/footer.css
Labels: Sylvain
